//! Schoolbook modular arithmetic over GF(p), generic over the limb count.
//!
//! ``FpNaive<L>`` stores a canonical residue ``v ∈ [0, p)`` as a ``Uint<L>``
//! and performs all operations with straightforward add-then-reduce logic.
//! It is the pedagogical baseline: correct, slow, easy to audit.
//!
//! The ``mul`` implementation widens to ``Uint<{2*L}>`` for the full product
//! and reduces via ``rem``.  Because ``2*L`` must be a compile-time constant
//! and Rust's const-generic arithmetic is limited on stable, the implementation
//! uses a fixed set of ``L``-specific ``impl`` blocks (``L = 1, 2, 4, 8``)
//! generated by a macro.  This covers all practical use cases without requiring
//! the nightly ``generic_const_exprs`` feature.

use crypto_bigint::{CheckedAdd, NonZero, Uint};

use super::Fp;

/// Schoolbook field element: canonical residue stored as a ``Uint<L>``.
///
/// All arithmetic is performed in canonical form (no internal encoding).
/// This makes the implementation easy to audit at the cost of performance.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FpNaive<const L: usize> {
    /// Canonical residue in ``[0, p)``.
    v: Uint<L>,
}

impl<const L: usize> FpNaive<L> {
    /// Wrap a pre-reduced value (must satisfy ``v < p``).
    #[inline]
    fn wrap(v: Uint<L>) -> Self {
        Self { v }
    }

    /// Reduce ``v mod p`` for a value known to be less than ``2p``.
    #[inline]
    fn reduce_once(v: Uint<L>, p: &Uint<L>) -> Uint<L> {
        if v >= *p { v.wrapping_sub(p) } else { v }
    }
}

/// Implement the complete ``Fp<L>`` trait for a specific limb count.
///
/// The ``mul`` method requires widening to ``Uint<{2*L}>``, which is not
/// expressible in stable Rust for arbitrary ``L``.  This macro generates a
/// complete ``impl Fp<$L> for FpNaive<$L>`` for each concrete ``($L, $DL)``
/// pair where ``$DL = 2 * $L``.
macro_rules! impl_fp_naive {
    ($L:literal, $DL:literal) => {
        impl Fp<$L> for FpNaive<$L> {
            fn zero(_p: &Uint<$L>) -> Self {
                Self::wrap(Uint::<$L>::ZERO)
            }

            fn one(_p: &Uint<$L>) -> Self {
                Self::wrap(Uint::<$L>::ONE)
            }

            fn from_u64(v: u64, p: &Uint<$L>) -> Self {
                let u = Uint::<$L>::from(v);
                let nz = NonZero::new(*p).expect("modulus must be non-zero");
                Self::wrap(u.rem(&nz))
            }

            fn from_uint(v: Uint<$L>, p: &Uint<$L>) -> Self {
                let nz = NonZero::new(*p).expect("modulus must be non-zero");
                Self::wrap(v.rem(&nz))
            }

            fn to_uint(&self) -> Uint<$L> {
                self.v
            }

            fn add(&self, rhs: &Self, p: &Uint<$L>) -> Self {
                // Sum fits in L+1 limbs at most; use wrapping add and subtract p once if needed.
                let s = self.v.checked_add(&rhs.v);
                let s = match s.into_option() {
                    Some(s) => s,
                    // Overflow: sum >= 2^(64*L), which exceeds any realistic p.
                    None => self.v.wrapping_add(&rhs.v),
                };
                Self::wrap(Self::reduce_once(s, p))
            }

            fn sub(&self, rhs: &Self, p: &Uint<$L>) -> Self {
                if self.v >= rhs.v {
                    Self::wrap(self.v.wrapping_sub(&rhs.v))
                } else {
                    // self < rhs: result = self + p - rhs
                    Self::wrap(p.wrapping_sub(&rhs.v).wrapping_add(&self.v))
                }
            }

            fn neg(&self, p: &Uint<$L>) -> Self {
                if self.v == Uint::<$L>::ZERO {
                    Self::wrap(Uint::<$L>::ZERO)
                } else {
                    Self::wrap(p.wrapping_sub(&self.v))
                }
            }

            fn mul(&self, rhs: &Self, p: &Uint<$L>) -> Self {
                // Widen to 2*L limbs for the full product, then reduce.
                // mul_wide returns (lo, hi): value = hi * 2^(L*64) + lo.
                let (lo, hi) = self.v.mul_wide(&rhs.v);
                // Uint::from((lo, hi)): value = hi * 2^(L*64) + lo.
                let wide = Uint::<$DL>::from((lo, hi));
                // Embed p into Uint<$DL> as a low-half value.
                let p_wide = Uint::<$DL>::from((*p, Uint::<$L>::ZERO));
                let nz = NonZero::new(p_wide).expect("modulus must be non-zero");
                let rem: Uint<$DL> = wide.rem(&nz);
                // rem < p < 2^(L*64), so its high L limbs are zero; extract the low L.
                let words = rem.as_words();
                let mut lo_words = [0u64; $L];
                lo_words.copy_from_slice(&words[..$L]);
                Self::wrap(Uint::<$L>::from_words(lo_words))
            }

            fn square(&self, p: &Uint<$L>) -> Self {
                self.mul(self, p)
            }

            fn pow(&self, exp: &Uint<$L>, p: &Uint<$L>) -> Self {
                // Square-and-multiply (right-to-left binary method).
                let mut result = Self::one(p);
                let mut base = self.clone();
                let mut e = *exp;
                while e != Uint::<$L>::ZERO {
                    if e.bit(0).into() {
                        result = result.mul(&base, p);
                    }
                    base = base.square(p);
                    e >>= 1;
                }
                result
            }

            fn inv(&self, p: &Uint<$L>) -> Self {
                assert!(!self.is_zero(p), "attempted inversion of zero");
                // Fermat: a^(p-2) mod p for prime p.
                let exp = p.wrapping_sub(&Uint::<$L>::from(2u64));
                self.pow(&exp, p)
            }
        }
    };
}

// Generate complete Fp<L> impls for each supported limb count.
impl_fp_naive!(1, 2);
impl_fp_naive!(2, 4);
impl_fp_naive!(4, 8);
impl_fp_naive!(8, 16);

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// secp256k1 prime: p = 2^256 - 2^32 - 977.
    fn secp_p() -> Uint<4> {
        Uint::<4>::from_be_hex(
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F",
        )
    }

    /// Small prime for cheap tests.
    fn p13() -> Uint<4> {
        Uint::<4>::from(13u64)
    }

    #[test]
    fn add_small() {
        let p = p13();
        let a = FpNaive::<4>::from_u64(7, &p);
        let b = FpNaive::<4>::from_u64(9, &p);
        // 7 + 9 = 16 ≡ 3 (mod 13)
        assert_eq!(a.add(&b, &p).to_uint(), Uint::<4>::from(3u64));
    }

    #[test]
    fn sub_wrap() {
        let p = p13();
        let a = FpNaive::<4>::from_u64(3, &p);
        let b = FpNaive::<4>::from_u64(7, &p);
        // 3 - 7 ≡ -4 ≡ 9 (mod 13)
        assert_eq!(a.sub(&b, &p).to_uint(), Uint::<4>::from(9u64));
    }

    #[test]
    fn mul_small() {
        let p = p13();
        let a = FpNaive::<4>::from_u64(5, &p);
        let b = FpNaive::<4>::from_u64(6, &p);
        // 5 * 6 = 30 ≡ 4 (mod 13)
        assert_eq!(a.mul(&b, &p).to_uint(), Uint::<4>::from(4u64));
    }

    #[test]
    fn inv_small() {
        let p = p13();
        let a = FpNaive::<4>::from_u64(5, &p);
        let ai = a.inv(&p);
        let one = a.mul(&ai, &p);
        assert_eq!(one, FpNaive::<4>::one(&p));
    }

    #[test]
    fn neg_zero_is_zero() {
        let p = p13();
        let z = FpNaive::<4>::zero(&p);
        assert_eq!(z.neg(&p), FpNaive::<4>::zero(&p));
    }

    #[test]
    fn add_neg_is_zero() {
        let p = secp_p();
        let a = FpNaive::<4>::from_u64(0xDEAD_BEEF, &p);
        let neg_a = a.neg(&p);
        let sum = a.add(&neg_a, &p);
        assert_eq!(sum, FpNaive::<4>::zero(&p));
    }

    #[test]
    fn mul_secp_prime() {
        // 2 * ((p+1)/2) = p+1 ≡ 1 (mod p) when p is odd.
        let p = secp_p();
        let two = FpNaive::<4>::from_u64(2, &p);
        // (p+1)/2: p is odd so this is exact.
        let half = (p.wrapping_add(&Uint::<4>::ONE)) >> 1;
        let half_fp = FpNaive::<4>::from_uint(half, &p);
        let one = two.mul(&half_fp, &p);
        assert_eq!(one, FpNaive::<4>::one(&p));
    }

    #[test]
    fn pow_fermat() {
        // Fermat's little theorem: a^p ≡ a (mod p) for prime p.
        let p = p13();
        let a = FpNaive::<4>::from_u64(7, &p);
        let ap = a.pow(&p, &p);
        assert_eq!(ap, a);
    }

    #[test]
    fn from_uint_reduces() {
        let p = p13();
        // p + 5 should reduce to 5.
        let big = p.wrapping_add(&Uint::<4>::from(5u64));
        let a = FpNaive::<4>::from_uint(big, &p);
        assert_eq!(a.to_uint(), Uint::<4>::from(5u64));
    }

    #[test]
    fn is_zero_and_is_one() {
        let p = p13();
        let z = FpNaive::<4>::zero(&p);
        let o = FpNaive::<4>::one(&p);
        assert!(z.is_zero(&p));
        assert!(!o.is_zero(&p));
        assert!(o.is_one(&p));
        assert!(!z.is_one(&p));
    }

    #[test]
    fn double_matches_add_self() {
        let p = p13();
        let a = FpNaive::<4>::from_u64(5, &p);
        assert_eq!(a.double(&p), a.add(&a, &p));
    }

    /// Verify that FpNaive<1> works for a small 1-limb prime.
    #[test]
    fn naive_1limb_basic() {
        let p = Uint::<1>::from(13u64);
        let a = FpNaive::<1>::from_u64(7, &p);
        let b = FpNaive::<1>::from_u64(9, &p);
        // 7 + 9 = 16 ≡ 3 (mod 13)
        assert_eq!(a.add(&b, &p).to_uint(), Uint::<1>::from(3u64));
        // 5 * 6 = 30 ≡ 4 (mod 13)
        let c = FpNaive::<1>::from_u64(5, &p);
        let d = FpNaive::<1>::from_u64(6, &p);
        assert_eq!(c.mul(&d, &p).to_uint(), Uint::<1>::from(4u64));
    }
}
