//! Normal-basis GF(2^m) arithmetic, generic over the limb count.
//!
//! `F2mNormal<L>` is a second implementor of the [`F2m`] trait.  It stores a
//! field element as a **normal-basis coefficient bit-vector**: bit `i` of the
//! stored value is the coefficient `aᵢ` in the expansion
//!
//! ```text
//! a = a₀·β + a₁·β² + a₂·β⁴ + … + a_{m−1}·β^(2^(m−1))
//! ```
//!
//! where `{β, β², …, β^(2^(m−1))}` is the normal basis generated by the
//! normal element `β`.
//!
//! # The pedagogical payoff: squaring is a cyclic shift
//!
//! In a normal basis, squaring is the Frobenius endomorphism `a → a²`.
//! Applying it to the expansion above:
//!
//! ```text
//! a² = Σ aᵢ · β^(2^(i+1))   (Frobenius is linear over GF(2))
//!    = a_{m−1}·β + a₀·β² + … + a_{m−2}·β^(2^(m−1))
//! ```
//!
//! The coefficient vector **rotates left by one position** (the last bit wraps
//! to the first).  This is the defining property of a normal basis and the
//! reason normal bases are used in hardware GF(2^m) implementations.
//!
//! The KATs in `shared/gf2m/tests/gf2m_kat.rs` verify this property directly:
//! `square(a).c == cyclic_left_shift(a.c, m)`.
//!
//! # Multiplication
//!
//! Multiplication in a normal basis uses the λ-matrix (the Massey–Omura
//! multiplication table).  For demonstration fidelity, this implementation
//! converts both operands to polynomial basis, multiplies there, and converts
//! back.  The λ-matrix optimisation is a principle-2 scale-only concern (E.F.4).
//!
//! # Storage contract
//!
//! **`c` is a normal-basis coefficient bit-vector, NOT an integer and NOT a
//! polynomial coefficient bit-vector.**  Bit `i` of `c` is the coefficient of
//! `β^(2^i)`.  Only XOR, cyclic-shift, and bit operations are meaningful on `c`
//! directly.  Arithmetic operations that require the field structure (`mul`,
//! `inv`, `from_uint`, `to_uint`) convert through the polynomial basis via
//! [`crate::convert`].
//!
//! # Normal element and irreducible
//!
//! Both the normal element `β` and the irreducible polynomial `poly` are stored
//! on the struct.  This is necessary because the `F2m` trait's `to_uint` takes
//! no `poly` parameter, yet converting from normal basis to the canonical
//! polynomial-basis `Uint<L>` requires both.  The `poly` field mirrors the
//! per-call `poly: &Uint<L>` of `F2mNaive` but is stored for the methods that
//! cannot receive it (primarily `to_uint`).
//!
//! Use [`crate::convert::find_normal_element`] to obtain a valid `beta` for a
//! given `poly`.

use crypto_bigint::Uint;

use crate::convert::{normal_to_poly, poly_to_normal};
use crate::naive::F2mNaive;
use crate::F2m;

/// Normal-basis GF(2^m) element.
///
/// Stores the field element as a normal-basis coefficient bit-vector `c`
/// (bit `i` = coefficient of `β^(2^i)`) together with the normal element
/// `beta` and the irreducible polynomial `poly` that define the field and basis.
///
/// # Invariants
///
/// - `beta` must be a normal element of GF(2^m) defined by `poly`.
/// - `c` must be a valid normal-basis coefficient vector (all bits above
///   position `m−1` are zero, where `m = poly.bits() − 1`).
///
/// Use [`crate::convert::find_normal_element`] to obtain a valid `beta`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct F2mNormal<const L: usize> {
    /// Normal-basis coefficient bit-vector: bit `i` is the coefficient of `β^(2^i)`.
    pub(crate) c: Uint<L>,
    /// Normal element `β` in polynomial-basis representation.
    pub(crate) beta: Uint<L>,
    /// Irreducible polynomial defining GF(2^m).
    ///
    /// Stored on the struct because `to_uint` (which converts to polynomial
    /// basis) takes no `poly` parameter in the `F2m` trait.
    pub(crate) poly: Uint<L>,
}

impl<const L: usize> F2mNormal<L> {
    /// Construct an `F2mNormal` from a normal-basis coefficient bit-vector.
    ///
    /// `c` must already be in normal-basis form.
    /// `beta` must be a normal element of GF(2^m) defined by `poly`.
    #[inline]
    #[must_use]
    pub fn from_normal_coords(c: Uint<L>, beta: Uint<L>, poly: Uint<L>) -> Self {
        Self { c, beta, poly }
    }

    /// Construct an `F2mNormal` from a polynomial-basis value.
    ///
    /// Converts `a_poly` to normal-basis coordinates using `beta` and `poly`.
    /// `beta` must be a normal element of GF(2^m) defined by `poly`.
    #[must_use]
    pub fn from_poly(a_poly: Uint<L>, beta: Uint<L>, poly: Uint<L>) -> Self
    where
        F2mNaive<L>: F2m<L>,
    {
        let c = poly_to_normal(&a_poly, &beta, &poly);
        Self { c, beta, poly }
    }

    /// Return the polynomial-basis representation of this element.
    #[must_use]
    pub fn to_poly_repr(&self) -> Uint<L>
    where
        F2mNaive<L>: F2m<L>,
    {
        normal_to_poly(&self.c, &self.beta, &self.poly)
    }

    /// Return the normal-basis coefficient bit-vector.
    ///
    /// Bit `i` of the returned value is the coefficient `aᵢ` of `β^(2^i)` in
    /// the normal-basis expansion `a = Σ aᵢ β^(2^i)`.
    ///
    /// This is the raw normal-basis representation — NOT the polynomial-basis
    /// coefficient bit-vector.  Use [`to_uint`] or [`to_poly_repr`] to obtain
    /// the polynomial-basis value.
    #[must_use]
    pub fn normal_coords(&self) -> Uint<L> {
        self.c
    }
}

/// Cyclic left-shift of the low `m` bits of a `u64` by 1 position.
///
/// Bit `m−1` wraps to bit `0`.  Bits above position `m−1` are zeroed.
/// This is the squaring operation in a normal basis.
#[inline]
pub(crate) fn cyclic_left_shift_m(v: u64, m: usize) -> u64 {
    debug_assert!(m > 0 && m <= 64, "cyclic_left_shift_m: m must be in 1..=64");
    let mask = if m == 64 { u64::MAX } else { (1u64 << m) - 1 };
    let top_bit = (v >> (m - 1)) & 1; // bit m−1 wraps to bit 0
    ((v << 1) | top_bit) & mask
}

/// Implement `F2m<L>` for `F2mNormal<L>` for a specific limb count.
///
/// The macro is needed because `mul`/`square` require widening to `Uint<{2*L}>`,
/// which is not expressible in stable Rust for arbitrary `L`.
macro_rules! impl_f2m_normal {
    ($L:literal) => {
        impl F2m<$L> for F2mNormal<$L> {
            fn zero() -> Self {
                // Zero in any basis is the all-zero coefficient vector.
                // beta and poly are unknown without arguments; use sentinel zeros.
                // Callers that need arithmetic should use from_uint(0, poly).
                Self {
                    c: Uint::<$L>::ZERO,
                    beta: Uint::<$L>::ZERO,
                    poly: Uint::<$L>::ZERO,
                }
            }

            fn one() -> Self {
                // Cannot construct the normal-basis representation of 1 without
                // knowing beta and poly.  Return a sentinel; callers that need
                // arithmetic should use from_uint(1, poly).
                //
                // is_one() is overridden below to avoid using to_uint() == ONE.
                Self {
                    c: Uint::<$L>::ZERO,
                    beta: Uint::<$L>::ZERO,
                    poly: Uint::<$L>::ZERO,
                }
            }

            fn from_u64(v: u64, poly: &Uint<$L>) -> Self {
                let u = Uint::<$L>::from(v);
                Self::from_uint(u, poly)
            }

            fn from_uint(v: Uint<$L>, poly: &Uint<$L>) -> Self
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // Reduce v mod poly (polynomial basis), then convert to normal basis.
                let beta = crate::convert::find_normal_element::<$L>(poly);
                // Reduce v to a valid polynomial-basis element.
                let a_poly = F2mNaive::<$L>::from_uint(v, poly).to_uint();
                let c = poly_to_normal(&a_poly, &beta, poly);
                Self { c, beta, poly: *poly }
            }

            fn to_uint(&self) -> Uint<$L>
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // Return the polynomial-basis representation as the canonical Uint<L>.
                // This is what F2mNaive::to_uint returns and what callers expect
                // (the C-F2m contract: to_uint returns the polynomial coefficient bit-vector).
                if self.poly == Uint::<$L>::ZERO {
                    // Sentinel zero/one — return c directly (which is 0).
                    return self.c;
                }
                normal_to_poly(&self.c, &self.beta, &self.poly)
            }

            fn add(&self, rhs: &Self) -> Self {
                // Addition in any basis is XOR of coefficient vectors.
                // No poly or beta needed — XOR is always in-field.
                Self {
                    c: self.c ^ rhs.c,
                    beta: self.beta,
                    poly: self.poly,
                }
            }

            fn sub(&self, rhs: &Self) -> Self {
                // sub == add in characteristic 2.
                self.add(rhs)
            }

            fn neg(&self) -> Self {
                // neg == identity in characteristic 2.
                self.clone()
            }

            fn square(&self, poly: &Uint<$L>) -> Self {
                // **THE PEDAGOGICAL PAYOFF**: squaring in a normal basis is a
                // cyclic left-shift of the coefficient vector by 1 position.
                //
                // Proof: a = Σ aᵢ β^(2^i)
                //        a² = Σ aᵢ β^(2^(i+1))   (Frobenius is linear over GF(2))
                //           = a_{m−1}·β + a₀·β² + … + a_{m−2}·β^(2^(m−1))
                //
                // The coefficient at position i of a² is a_{i−1 mod m}.
                // This is a cyclic left-shift of the coefficient vector.
                let m = poly.bits() - 1;
                // Work in the low 64 bits (m ≤ 64 for all toy fields).
                let c_bits = self.c.as_words()[0];
                let shifted = cyclic_left_shift_m(c_bits, m);
                let new_c = Uint::<$L>::from(shifted);
                Self {
                    c: new_c,
                    beta: self.beta,
                    poly: self.poly,
                }
            }

            fn frobenius(&self, poly: &Uint<$L>) -> Self {
                // Frobenius endomorphism a → a² is exactly squaring.
                self.square(poly)
            }

            fn mul(&self, rhs: &Self, poly: &Uint<$L>) -> Self
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // Convert both operands to polynomial basis, multiply there,
                // convert back.  This is the correct approach for a pedagogical
                // implementation; the λ-matrix optimisation is E.F.4.
                let a_poly = normal_to_poly(&self.c, &self.beta, poly);
                let b_poly = normal_to_poly(&rhs.c, &self.beta, poly);
                let a_naive = F2mNaive::<$L>::from_uint(a_poly, poly);
                let b_naive = F2mNaive::<$L>::from_uint(b_poly, poly);
                let prod_poly = a_naive.mul(&b_naive, poly).to_uint();
                let prod_c = poly_to_normal(&prod_poly, &self.beta, poly);
                Self {
                    c: prod_c,
                    beta: self.beta,
                    poly: self.poly,
                }
            }

            fn pow(&self, exp: &Uint<$L>, poly: &Uint<$L>) -> Self
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // Square-and-multiply using the normal-basis square (cyclic shift).
                // The identity element in normal basis: poly_to_normal(1, beta, poly).
                let one_c = poly_to_normal(&Uint::<$L>::ONE, &self.beta, poly);
                let mut result = Self {
                    c: one_c,
                    beta: self.beta,
                    poly: self.poly,
                };
                let mut base = self.clone();
                let mut e = *exp;
                while e != Uint::<$L>::ZERO {
                    if e.bit(0).into() {
                        result = result.mul(&base, poly);
                    }
                    base = base.square(poly);
                    e >>= 1;
                }
                result
            }

            fn trace(&self, _poly: &Uint<$L>) -> Self {
                unimplemented!("E.G")
            }

            fn solve_quadratic(_c: &Self, _poly: &Uint<$L>) -> Self {
                unimplemented!("E.G")
            }

            fn inv(&self, poly: &Uint<$L>) -> Self
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // Convert to polynomial basis, invert there, convert back.
                assert!(!self.is_zero(), "F2mNormal::inv: zero has no multiplicative inverse");
                let a_poly = normal_to_poly(&self.c, &self.beta, poly);
                let a_naive = F2mNaive::<$L>::from_uint(a_poly, poly);
                let inv_poly = a_naive.inv(poly).to_uint();
                let inv_c = poly_to_normal(&inv_poly, &self.beta, poly);
                Self {
                    c: inv_c,
                    beta: self.beta,
                    poly: self.poly,
                }
            }

            fn div(&self, rhs: &Self, poly: &Uint<$L>) -> Self {
                // a / b = a * b⁻¹.  Panics if rhs is zero.
                self.mul(&rhs.inv(poly), poly)
            }

            fn is_zero(&self) -> bool {
                // Zero in any basis is the all-zero coefficient vector.
                self.c == Uint::<$L>::ZERO
            }

            fn is_one(&self) -> bool
            where
                F2mNaive<$L>: F2m<$L>,
            {
                // One in normal basis is poly_to_normal(1, beta, poly).
                // We compare to_uint() (polynomial basis) against 1.
                if self.poly == Uint::<$L>::ZERO {
                    return false; // sentinel
                }
                self.to_uint() == Uint::<$L>::ONE
            }
        }
    };
}

impl_f2m_normal!(1);
impl_f2m_normal!(2);
impl_f2m_normal!(4);
impl_f2m_normal!(8);

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::convert::find_normal_element;

    fn poly4() -> Uint<1> {
        Uint::<1>::from(0x13u64)
    }

    fn poly8() -> Uint<1> {
        Uint::<1>::from(0x11bu64)
    }

    #[test]
    fn square_is_cyclic_shift_gf4() {
        let p = poly4();
        let m = p.bits() - 1; // 4
        let beta = find_normal_element(&p);

        // For every element, verify square(a).c == cyclic_left_shift(a.c, m).
        for v in 0u64..16 {
            let a = F2mNormal::<1>::from_uint(Uint::<1>::from(v), &p);
            let sq = a.square(&p);
            let c_bits = a.c.as_words()[0];
            let expected_c = cyclic_left_shift_m(c_bits, m);
            assert_eq!(
                sq.c.as_words()[0],
                expected_c,
                "square is not a cyclic shift for v={v:#x} (normal coords={c_bits:#06b})"
            );
            assert_eq!(sq.beta, beta);
        }
    }

    #[test]
    fn add_is_xor_gf4() {
        let p = poly4();
        let beta = find_normal_element(&p);
        let a = F2mNormal::<1>::from_normal_coords(
            Uint::<1>::from(0b0101u64),
            beta,
            p,
        );
        let b = F2mNormal::<1>::from_normal_coords(
            Uint::<1>::from(0b0011u64),
            beta,
            p,
        );
        assert_eq!(a.add(&b).c, Uint::<1>::from(0b0110u64));
    }

    #[test]
    fn mul_agrees_with_naive_gf4() {
        let p = poly4();
        let beta = find_normal_element(&p);
        // Pick two elements in polynomial basis, convert to normal, multiply,
        // convert back, compare with naive mul.
        let av = 0b0110u64;
        let bv = 0b1011u64;
        let a_poly = Uint::<1>::from(av);
        let b_poly = Uint::<1>::from(bv);
        let a_norm = F2mNormal::<1>::from_poly(a_poly, beta, p);
        let b_norm = F2mNormal::<1>::from_poly(b_poly, beta, p);
        let prod_norm = a_norm.mul(&b_norm, &p);
        let prod_poly = prod_norm.to_poly_repr();

        let a_naive = F2mNaive::<1>::from_uint(a_poly, &p);
        let b_naive = F2mNaive::<1>::from_uint(b_poly, &p);
        let expected = a_naive.mul(&b_naive, &p).to_uint();

        assert_eq!(prod_poly, expected, "normal-basis mul disagrees with naive mul");
    }

    #[test]
    fn square_agrees_with_naive_gf8() {
        let p = poly8();
        for v in 0u64..256 {
            let a_norm = F2mNormal::<1>::from_uint(Uint::<1>::from(v), &p);
            let sq_norm = a_norm.square(&p);
            let sq_poly = sq_norm.to_poly_repr();

            let a_naive = F2mNaive::<1>::from_uint(Uint::<1>::from(v), &p);
            let sq_naive = a_naive.square(&p).to_uint();

            assert_eq!(
                sq_poly, sq_naive,
                "normal square disagrees with naive square for v={v:#x}"
            );
        }
    }
}
