//! Ideal representation in ℤ[α]: two-element primary form `(p, α − r)`.
//!
//! An ideal `I = (p, α − r)` is the ℤ[α]-ideal generated by the rational prime `p`
//! and the element `α − r`. This is the standard two-element representation used in
//! the Number Field Sieve.

use num_bigint::BigInt;
use num_traits::{One, Signed, Zero};

use crate::element::NumberField;

// ─── Ideal ───────────────────────────────────────────────────────────────────

/// A fractional ideal of ℤ[α] in two-element representation.
///
/// Primary representation: I = (p, α − r) where p is a rational prime and r ∈ ℤ.
/// This represents the ideal generated by p and (α − r) in ℤ[α].
///
/// Invariant: p > 0.
pub struct Ideal<'a> {
    pub field: &'a NumberField,
    /// The rational prime p.
    pub p: BigInt,
    /// The integer r such that (α − r) is the second generator.
    pub r: BigInt,
}

impl<'a> Ideal<'a> {
    /// Construct the ideal (p, α − r).
    ///
    /// Panics if p ≤ 0.
    pub fn new(field: &'a NumberField, p: BigInt, r: BigInt) -> Self {
        assert!(p.is_positive(), "ideal prime p must be positive, got {p}");
        Self { field, p, r }
    }

    /// The rational prime p (first generator).
    pub fn prime(&self) -> &BigInt {
        &self.p
    }

    /// The integer r (second generator, giving α − r).
    pub fn r(&self) -> &BigInt {
        &self.r
    }

    /// Ideal norm: N(I) = p.
    ///
    /// For a prime ideal (p, α − r) above a rational prime p where p ∤ disc(f),
    /// the residue degree is 1 in the standard NFS setup, so N(I) = p.
    pub fn norm(&self) -> BigInt {
        self.p.clone()
    }

    /// Ideal multiplication: (p₁, α − r₁) · (p₂, α − r₂).
    ///
    /// For the NFS use case, the product of two prime ideals above distinct primes
    /// p₁ ≠ p₂ is represented as (p₁·p₂, α − r) where r is determined by CRT:
    /// r ≡ r₁ (mod p₁), r ≡ r₂ (mod p₂).
    ///
    /// Computes r via CRT: r = r₁ + p₁ · ((r₂ − r₁) · p₁⁻¹ mod p₂), then reduces mod p₁·p₂.
    ///
    /// Panics if p₁ and p₂ are not coprime (gcd ≠ 1).
    pub fn mul(&self, rhs: &Self) -> Self {
        let p = &self.p * &rhs.p;

        // CRT: find r such that r ≡ r₁ (mod p₁) and r ≡ r₂ (mod p₂).
        // r = r₁ + p₁ · ((r₂ − r₁) · p₁⁻¹ mod p₂)
        let diff = &rhs.r - &self.r;
        let p1_inv_mod_p2 = mod_inverse(&self.p, &rhs.p)
            .expect("p₁ and p₂ must be coprime for ideal multiplication");
        // ((r₂ − r₁) · p₁⁻¹) mod p₂
        let t = mod_reduce(&(diff * &p1_inv_mod_p2), &rhs.p);
        let r_raw = &self.r + &self.p * t;
        // Reduce r into [0, p₁·p₂)
        let r = mod_reduce(&r_raw, &p);

        Self { field: self.field, p, r }
    }
}

impl PartialEq for Ideal<'_> {
    fn eq(&self, other: &Self) -> bool {
        self.p == other.p && self.r == other.r
    }
}

impl Eq for Ideal<'_> {}

impl std::fmt::Debug for Ideal<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Ideal(p={}, r={})", self.p, self.r)
    }
}

// ─── Modular arithmetic helpers ───────────────────────────────────────────────

/// Reduce `a` into the canonical range [0, m) for m > 0.
fn mod_reduce(a: &BigInt, m: &BigInt) -> BigInt {
    let r = a % m;
    if r.is_negative() { r + m } else { r }
}

/// Compute the modular inverse of `a` modulo `m` using the extended Euclidean algorithm.
///
/// Returns `Some(x)` such that `a * x ≡ 1 (mod m)`, or `None` if gcd(a, m) ≠ 1.
fn mod_inverse(a: &BigInt, m: &BigInt) -> Option<BigInt> {
    let (gcd, x, _) = extended_gcd(a, m);
    if gcd != BigInt::one() {
        return None;
    }
    Some(mod_reduce(&x, m))
}

/// Extended Euclidean algorithm over ℤ.
///
/// Returns `(gcd, s, t)` such that `s * a + t * b = gcd` and `gcd ≥ 0`.
fn extended_gcd(a: &BigInt, b: &BigInt) -> (BigInt, BigInt, BigInt) {
    let mut old_r = a.clone();
    let mut r = b.clone();
    let mut old_s = BigInt::one();
    let mut s = BigInt::zero();
    let mut old_t = BigInt::zero();
    let mut t = BigInt::one();

    while !r.is_zero() {
        // Euclidean division: old_r = q * r + rem
        let q = &old_r / &r;
        let rem = &old_r - &q * &r;
        old_r = r;
        r = rem;
        let new_s = old_s - &q * &s;
        old_s = s;
        s = new_s;
        let new_t = old_t - &q * &t;
        old_t = t;
        t = new_t;
    }

    // Ensure gcd is non-negative
    if old_r.is_negative() {
        (-old_r, -old_s, -old_t)
    } else {
        (old_r, old_s, old_t)
    }
}

// ─── Unit tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::poly::IntPoly;

    fn bi(n: i64) -> BigInt {
        BigInt::from(n)
    }

    /// f = x² − 2 (defines ℚ(√2))
    fn field_sqrt2() -> NumberField {
        NumberField::new(IntPoly::from_coeffs(vec![bi(-2), bi(0), bi(1)]))
    }

    #[test]
    fn new_panics_on_zero_p() {
        let k = field_sqrt2();
        let result = std::panic::catch_unwind(|| {
            Ideal::new(&k, bi(0), bi(1));
        });
        assert!(result.is_err(), "Ideal::new should panic when p = 0");
    }

    #[test]
    fn new_panics_on_negative_p() {
        let k = field_sqrt2();
        let result = std::panic::catch_unwind(|| {
            Ideal::new(&k, bi(-5), bi(1));
        });
        assert!(result.is_err(), "Ideal::new should panic when p < 0");
    }

    #[test]
    fn mod_inverse_basic() {
        // 3⁻¹ mod 7 = 5 (since 3·5 = 15 ≡ 1 mod 7)
        let inv = mod_inverse(&bi(3), &bi(7)).unwrap();
        assert_eq!(inv, bi(5));
    }

    #[test]
    fn extended_gcd_basic() {
        // gcd(12, 8) = 4; 4 = 1·12 + (-1)·8
        let (g, s, t) = extended_gcd(&bi(12), &bi(8));
        assert_eq!(g, bi(4));
        assert_eq!(s.clone() * bi(12) + t.clone() * bi(8), bi(4));
    }
}
