//! GLV endomorphism (order-3) for the secp-toy curve.
//!
//! The Frobenius endomorphism `φ(x, y) = (β·x mod p, y)` satisfies `φ(P) = λ·P`
//! for all points P on the secp_k1_toy curve.  Because φ has order 3 (`φ³ = id`),
//! the orbit of any point P under the group generated by φ and negation is
//! `{P, φ(P), φ²(P), −P, −φ(P), −φ²(P)}` — a set of size 6 (for generic P).
//!
//! Collapsing this 6-orbit to a single canonical representative reduces the
//! effective group size by a factor of 6, dropping the expected rho steps by √6
//! vs the plain walk and √3 vs the negation-map-only walk.
//!
//! # Canonical representative
//!
//! The canonical element is the orbit member with the numerically smallest
//! x-coordinate (comparing canonical residues in `[0, p)`).  On a tie (impossible
//! for generic points on this curve), the smaller y-coordinate breaks the tie.
//!
//! # Scalar adjustment
//!
//! If the current walk state satisfies `W = a·G + b·Q`, then:
//!
//! | Orbit member | Point      | a-factor      | b-factor      |
//! |--------------|------------|---------------|---------------|
//! | 0            | W          | a             | b             |
//! | 1            | φ(W)       | λa mod n      | λb mod n      |
//! | 2            | φ²(W)      | λ²a mod n     | λ²b mod n     |
//! | 3            | −W         | n−a (mod n)   | n−b (mod n)   |
//! | 4            | −φ(W)      | n−λa (mod n)  | n−λb (mod n)  |
//! | 5            | −φ²(W)     | n−λ²a (mod n) | n−λ²b (mod n) |

use crypto_bigint::Uint;

use shared_field::Fp;

use crate::curve::AffinePoint;

// ── GLV endomorphism ──────────────────────────────────────────────────────────

/// Apply the GLV endomorphism: `φ(x, y) = (β·x mod p, y)`.
///
/// Returns the image point.  Note that `φ²(P) = φ(φ(P))`.
///
/// # Arguments
///
/// * `pt` — the input point.
/// * `p_modulus` — the field prime.
/// * `beta` — the cube root of unity mod p (satisfies β³ ≡ 1 mod p, β ≠ 1).
pub fn glv_phi<F: Fp<4>>(pt: &AffinePoint<F>, p_modulus: &Uint<4>, beta: u64) -> AffinePoint<F> {
    match pt {
        AffinePoint::Infinity => AffinePoint::Infinity,
        AffinePoint::Finite { x, y } => {
            let x_uint = x.to_uint();
            let new_x_uint = beta_mul(x_uint, p_modulus, beta);
            AffinePoint::Finite {
                x: F::from_uint(new_x_uint, p_modulus),
                y: y.clone(),
            }
        }
    }
}

/// Compute `β·x mod p` using widening multiplication.
#[inline]
pub(crate) fn beta_mul(x: Uint<4>, p: &Uint<4>, beta: u64) -> Uint<4> {
    let beta_u = Uint::<4>::from(beta);
    let (lo, hi) = beta_u.mul_wide(&x);
    let wide = crypto_bigint::Uint::<8>::from((lo, hi));
    let p8 = crypto_bigint::Uint::<8>::from((*p, Uint::<4>::ZERO));
    let nz = crypto_bigint::NonZero::new(p8).expect("p is non-zero");
    let rem8 = wide.rem(&nz);
    let words = rem8.as_words();
    Uint::<4>::from_words([words[0], words[1], words[2], words[3]])
}

// ── Orbit and canonical representative ───────────────────────────────────────

/// Compute the canonical representative of the 6-orbit `{P, φ(P), φ²(P), −P, −φ(P), −φ²(P)}`.
///
/// Returns `(canonical_point, adjusted_a, adjusted_b)` where the adjusted scalars
/// satisfy `canonical_point = adjusted_a·G + adjusted_b·Q`, given that the input
/// satisfies `pt = a·G + b·Q`.
///
/// The canonical element is the orbit member with the smallest x-coordinate.
/// On a tie (impossible for generic points), the smaller y-coordinate wins.
///
/// # Arguments
///
/// * `pt` — current walk point (satisfies `pt = a·G + b·Q`).
/// * `a` — scalar coefficient for G.
/// * `b` — scalar coefficient for Q.
/// * `p_modulus` — field prime.
/// * `n` — group order.
/// * `beta` — cube root of unity mod p (GLV endomorphism constant).
/// * `lambda` — GLV eigenvalue mod n (satisfies λ² + λ + 1 ≡ 0 mod n).
pub fn glv_canonical<F: Fp<4>>(
    pt: &AffinePoint<F>,
    a: u64,
    b: u64,
    p_modulus: &Uint<4>,
    n: u64,
    beta: u64,
    lambda: u64,
) -> (AffinePoint<F>, u64, u64) {
    // Infinity is its own canonical representative.
    let (x_orig, y_orig) = match pt {
        AffinePoint::Infinity => return (AffinePoint::Infinity, a, b),
        AffinePoint::Finite { x, y } => (x, y),
    };

    // Precompute λ and λ² mod n for scalar adjustments.
    let lam2 = mulmod64(lambda, lambda, n);

    // Precompute the three x-coordinates (shared by positive and negative orbit members).
    let x0 = x_orig.to_uint();                         // x of P
    let x1 = beta_mul(x0, p_modulus, beta);            // x of φ(P)
    let x2 = beta_mul(x1, p_modulus, beta);            // x of φ²(P)

    // Negation shares the same x-coordinates; y-coordinates are p − y.
    let y_uint = y_orig.to_uint();
    let neg_y_uint = p_modulus.wrapping_sub(&y_uint);

    // Build the 6 orbit members as (x_uint, y_uint, a_adj, b_adj).
    // We avoid constructing full AffinePoint<F> until we know the winner.
    let candidates: [(Uint<4>, Uint<4>, u64, u64); 6] = [
        (x0, y_uint,     a,                                       b),
        (x1, y_uint,     mulmod64(lambda, a, n),                  mulmod64(lambda, b, n)),
        (x2, y_uint,     mulmod64(lam2,   a, n),                  mulmod64(lam2,   b, n)),
        (x0, neg_y_uint, negate_scalar(a, n),                     negate_scalar(b, n)),
        (x1, neg_y_uint, negate_scalar(mulmod64(lambda, a, n), n),
                         negate_scalar(mulmod64(lambda, b, n), n)),
        (x2, neg_y_uint, negate_scalar(mulmod64(lam2,   a, n), n),
                         negate_scalar(mulmod64(lam2,   b, n), n)),
    ];

    // Find the orbit member with the smallest x (tie-break: smallest y).
    let mut best = 0usize;
    for i in 1..6 {
        let (cx, cy, _, _) = &candidates[i];
        let (bx, by, _, _) = &candidates[best];
        if cx < bx || (cx == bx && cy < by) {
            best = i;
        }
    }

    let (win_x, win_y, win_a, win_b) = &candidates[best];
    let canon = AffinePoint::Finite {
        x: F::from_uint(*win_x, p_modulus),
        y: F::from_uint(*win_y, p_modulus),
    };
    (canon, *win_a, *win_b)
}

// ── Scalar helpers ────────────────────────────────────────────────────────────

/// Modular multiplication of two 64-bit values mod `n`.
#[inline]
pub(crate) fn mulmod64(a: u64, b: u64, n: u64) -> u64 {
    ((a as u128 * b as u128) % n as u128) as u64
}

/// Negate a scalar: `n − a` (mod n), with `0 ↦ 0`.
#[inline]
fn negate_scalar(a: u64, n: u64) -> u64 {
    if a == 0 { 0 } else { n - a }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crypto_bigint::Uint;
    use shared_field::FpMonty4 as FpMonty;

    use crate::curve::AffinePoint;
    use crate::curve::secp_k1_toy::{secp_k1_toy, P, N as SECP_N, BETA, LAMBDA};

    // ── Endomorphism order ────────────────────────────────────────────────────

    /// φ has order 3: φ(φ(φ(P))) = P for any point P.
    #[test]
    fn phi_order_three() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        for k in [1u64, 2, 3, 7, 42, 100, LAMBDA] {
            let pt = curve.scalar_mul(&g, &Uint::<4>::from(k));
            let phi1 = glv_phi(&pt, &p_mod, BETA);
            let phi2 = glv_phi(&phi1, &p_mod, BETA);
            let phi3 = glv_phi(&phi2, &p_mod, BETA);
            assert_eq!(phi3, pt, "φ³(P) ≠ P for k={k}");
        }
    }

    /// φ(P) is on the curve for every test point.
    #[test]
    fn phi_image_on_curve() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        for k in [1u64, 2, 5, 13, 99] {
            let pt = curve.scalar_mul(&g, &Uint::<4>::from(k));
            let phi_pt = glv_phi(&pt, &p_mod, BETA);
            assert!(curve.is_on_curve(&phi_pt), "φ(P) not on curve for k={k}");
        }
    }

    // ── 6-orbit tests ─────────────────────────────────────────────────────────

    /// The 6 orbit members are distinct and all on the curve.
    #[test]
    fn glv_orbit_size_6() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        // Use k=7 as a generic point (not a special-case like 1 or n/2).
        let pt = curve.scalar_mul(&g, &Uint::<4>::from(7u64));

        let phi1 = glv_phi(&pt, &p_mod, BETA);
        let phi2 = glv_phi(&phi1, &p_mod, BETA);
        let neg_pt   = curve.negate(&pt);
        let neg_phi1 = curve.negate(&phi1);
        let neg_phi2 = curve.negate(&phi2);

        let orbit = [pt.clone(), phi1.clone(), phi2.clone(), neg_pt, neg_phi1, neg_phi2];

        // All 6 are on the curve.
        for (i, member) in orbit.iter().enumerate() {
            assert!(curve.is_on_curve(member), "orbit member {i} not on curve");
        }

        // All 6 are distinct.
        for i in 0..6 {
            for j in (i + 1)..6 {
                assert_ne!(orbit[i], orbit[j], "orbit members {i} and {j} are equal");
            }
        }
    }

    /// glv_canonical returns a point that is one of the 6 orbit members.
    #[test]
    fn glv_canonical_is_orbit_member() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        for k in [3u64, 7, 42, 100, 999, 12345] {
            let pt = curve.scalar_mul(&g, &Uint::<4>::from(k));
            let a: u64 = 1;
            let b: u64 = 0;
            let (canon, _, _) = glv_canonical(&pt, a, b, &p_mod, SECP_N, BETA, LAMBDA);

            let phi1 = glv_phi(&pt, &p_mod, BETA);
            let phi2 = glv_phi(&phi1, &p_mod, BETA);
            let neg_pt   = curve.negate(&pt);
            let neg_phi1 = curve.negate(&phi1);
            let neg_phi2 = curve.negate(&phi2);

            let orbit = [pt, phi1, phi2, neg_pt, neg_phi1, neg_phi2];
            assert!(
                orbit.iter().any(|m| *m == canon),
                "canonical rep for k={k} is not in the orbit"
            );
        }
    }

    /// After glv_canonical, the invariant `canonical = adjusted_a·G + adjusted_b·Q` holds.
    #[test]
    fn glv_scalar_adjust() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        // Use k_target = 42 so Q = 42·G.
        let k_target: u64 = 42;
        let q = curve.scalar_mul(&g, &Uint::<4>::from(k_target));

        // Choose arbitrary (a, b) and compute W = a·G + b·Q.
        let a: u64 = 300;
        let b: u64 = 500;
        let ag = curve.scalar_mul(&g, &Uint::<4>::from(a));
        let bq = curve.scalar_mul(&q, &Uint::<4>::from(b));
        let w = curve.add_mixed(
            &crate::curve::JacobianPoint::from_affine(&ag, &p_mod),
            &bq,
        ).to_affine(&p_mod);

        let (canon, adj_a, adj_b) = glv_canonical(&w, a, b, &p_mod, SECP_N, BETA, LAMBDA);

        // Reconstruct adj_a·G + adj_b·Q and verify it equals canon.
        let adj_ag = curve.scalar_mul(&g, &Uint::<4>::from(adj_a));
        let adj_bq = curve.scalar_mul(&q, &Uint::<4>::from(adj_b));
        let reconstructed = curve.add_mixed(
            &crate::curve::JacobianPoint::from_affine(&adj_ag, &p_mod),
            &adj_bq,
        ).to_affine(&p_mod);

        assert_eq!(
            reconstructed, canon,
            "glv_scalar_adjust: adj_a·G + adj_b·Q ≠ canonical point"
        );
    }

    /// glv_canonical is idempotent: applying it twice gives the same result.
    #[test]
    fn glv_canonical_idempotent() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        for k in [5u64, 17, 99, 1000] {
            let pt = curve.scalar_mul(&g, &Uint::<4>::from(k));
            let (canon1, a1, b1) = glv_canonical(&pt, 1, 0, &p_mod, SECP_N, BETA, LAMBDA);
            let (canon2, a2, b2) = glv_canonical(&canon1, a1, b1, &p_mod, SECP_N, BETA, LAMBDA);
            assert_eq!(canon1, canon2, "glv_canonical not idempotent for k={k}");
            assert_eq!(a1, a2, "a not stable after second application for k={k}");
            assert_eq!(b1, b2, "b not stable after second application for k={k}");
        }
    }

    /// The canonical x-coordinate is the minimum x across all 6 orbit members.
    #[test]
    fn canonical_has_minimum_x() {
        let curve = secp_k1_toy();
        let p_mod = Uint::<4>::from(P);
        let g: AffinePoint<FpMonty> = curve.generator();

        for k in [2u64, 7, 50, 200] {
            let pt = curve.scalar_mul(&g, &Uint::<4>::from(k));
            let (canon, _, _) = glv_canonical(&pt, 1, 0, &p_mod, SECP_N, BETA, LAMBDA);

            let phi1 = glv_phi(&pt, &p_mod, BETA);
            let phi2 = glv_phi(&phi1, &p_mod, BETA);
            let neg_pt   = curve.negate(&pt);
            let neg_phi1 = curve.negate(&phi1);
            let neg_phi2 = curve.negate(&phi2);

            let orbit = [pt, phi1, phi2, neg_pt, neg_phi1, neg_phi2];
            let canon_x = canon.x().unwrap().to_uint();

            for (i, member) in orbit.iter().enumerate() {
                let mx = member.x().unwrap().to_uint();
                assert!(
                    canon_x <= mx,
                    "canonical x > orbit member {i} x for k={k}: {canon_x:?} > {mx:?}"
                );
            }
        }
    }
}
